demo:
    modelFile: config/perfect_cat_image.txt

logging:
  level:
    org.springframework: ERROR
    demo: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: demo.log